version: "3.8"
services:

    db:
        image: mysql
        container_name: db_docker_containerName
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_USER: ''
            MYSQL_PASSWORD: ''
            MYSQL_DATABASE: ''
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_containerName
        restart: always
        depends_on:
            - db
        ports:
            - 8082:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: maildev_docker_containerName
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
            - "8081:80"
        restart: always
        networks:
            - dev

    www:
        build: docker/php
        container_name: www_docker_containerName
        ports:
            - "8080:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./app:/var/www
        restart: always
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: